### ISSUE TITLE
Getting social icons and fonts working

### ISSUE THREAD

**Issue by ridkadri** [creativetimofficial/blk-design-system-react#3]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Put the code for social icons and fonts in my index.html folder but doesnt seem to work

# Current Behavior

Social icons and fonts code doesnt work

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

**Comment by EINazare** [comment]
Hello there @ridkadri ,

Thank you for your interest in working with our products.
Sorry for this late response, since I am a Christian I've had some free days for the Easter Holiday:

https://www.calendar-12.com/holidays/easter
https://www.officeholidays.com/religious/orthodox/orthodox_easter.php

Please read our whole docs here: https://demos.creative-tim.com/blk-design-system-react/#/documentation/overview
You will find the solution for your question there.

All the best,
Manu
ReactJS Developer at Creative-Tim.com (http://creative-tim.com/)

Trying to help the open source community:

* https://medium.freecodecamp.org/how-to-use-reactjs-with-webpack-4-babel-7-and-material-design-ff754586f618
* https://medium.freecodecamp.org/how-to-use-redux-in-reactjs-with-real-life-examples-687ab4441b85
* https://medium.freecodecamp.org/how-to-connect-a-react-design-system-with-firebase-and-redux-9646ca1c733f



* https://www.youtube.com/watch?v=raKV5Rb8oOM&list=PLWxSJr7LCl87rGlQtTo2PoX8hboUU0R8a
* https://www.youtube.com/watch?v=no2PD2kq-dE&list=PLWxSJr7LCl87OomktWFQVW30QDWtBqFlx



* https://www.udemy.com/learn-reactjs-with-webpack-4-babel-7-and-material-design/


If you've liked what you saw, help me with a comment, like, share or subscribe.

**Comment by ridkadri** [comment]
Hello Emmanuel, i have thoroughly read your documentation. i added the code to my html file to get icons and fonts working but didn’t work. Your documentation also didn’t point out the right packages to install to make it work. id attach the issues I’m having to this email. Thanks

**Comment by EINazare** [comment]
Hello again, @ridkadri ,

Please give me a detailed step by step of what you did with our product.
If I download the product, both from [https://www.creative-tim.com](https://www.creative-tim.com?ref=blkdsr-github-issues) or from [github](https://github.com/creativetimofficial/blk-design-system-react), everything seems to work flawlessly.

Will wait for your response.

All the best,
Manu
ReactJS Developer at Creative-Tim.com (http://creative-tim.com/)

Trying to help the open source community:

* https://medium.freecodecamp.org/how-to-use-reactjs-with-webpack-4-babel-7-and-material-design-ff754586f618
* https://medium.freecodecamp.org/how-to-use-redux-in-reactjs-with-real-life-examples-687ab4441b85
* https://medium.freecodecamp.org/how-to-connect-a-react-design-system-with-firebase-and-redux-9646ca1c733f



* https://www.youtube.com/watch?v=raKV5Rb8oOM&list=PLWxSJr7LCl87rGlQtTo2PoX8hboUU0R8a
* https://www.youtube.com/watch?v=no2PD2kq-dE&list=PLWxSJr7LCl87OomktWFQVW30QDWtBqFlx



* https://www.udemy.com/learn-reactjs-with-webpack-4-babel-7-and-material-design/


If you've liked what you saw, help me with a comment, like, share or subscribe.

**Comment by ridkadri** [comment]
Hello there, so i found out the reason my icons wasn’t showing up was because of "fab fa-twitter" instead of "fa fa-twitter". issue was for font icons. surprisingly fab doesn’t seem to work with React. And can you also leme know where exactly in html file i should put in the font and icons code

**Comment by EINazare** [comment]
Hello again, @ridkadri ,

So the fonts and icons should be added inside your index.html file (in React there should be just one index.html file, and in our product is found inside `public/index.html`).
But this is covered in our live docs here: https://demos.creative-tim.com/blk-design-system-react/#/documentation/tutorial (scroll down the page).
Also, fab should work, here is an image (I've added some red squares):
![Screen Shot 2019-05-03 at 10 55 00 AM](https://user-images.githubusercontent.com/26245512/57125424-149d0b80-6d92-11e9-8f74-23a1a360314d.png)

All the best,
Manu
ReactJS Developer at Creative-Tim.com (http://creative-tim.com/)

Trying to help the open source community:

* https://medium.freecodecamp.org/how-to-use-reactjs-with-webpack-4-babel-7-and-material-design-ff754586f618
* https://medium.freecodecamp.org/how-to-use-redux-in-reactjs-with-real-life-examples-687ab4441b85
* https://medium.freecodecamp.org/how-to-connect-a-react-design-system-with-firebase-and-redux-9646ca1c733f



* https://www.youtube.com/watch?v=raKV5Rb8oOM&list=PLWxSJr7LCl87rGlQtTo2PoX8hboUU0R8a
* https://www.youtube.com/watch?v=no2PD2kq-dE&list=PLWxSJr7LCl87OomktWFQVW30QDWtBqFlx



* https://www.udemy.com/learn-reactjs-with-webpack-4-babel-7-and-material-design/


If you've liked what you saw, help me with a comment, like, share or subscribe.

**Comment by EINazare** [comment]
@ridkadri , you should open my last comment on Github, do not read it from your email.
